#!/usr/bin/env python3

from rigol import *
from common import *
import sys
import os
import argparse

script_name = os.path.basename(sys.argv[0])
filepath = os.getcwd()

parser = argparse.ArgumentParser(description='Rigol DM3058 Digital Multimeter data capture.')
parser.add_argument("ip_address", nargs='?', default=None,
                    help=("IP address of a network or a host. Can be "
                          "IPv4 or IPv6 address"))
parser.add_argument("-I", "--imgur", action='store_true',
                    help="Upload to Imgur")
parser.add_argument("-P", "--preview", action='store_true',
                    help="Preview Image")

args = parser.parse_args()

if args.ip_address is not None:
    INSTRUMENT_IP = args.ip_address
else:
    INSTRUMENT_IP = find_arp(RIGOL_OUI)
    if INSTRUMENT_IP is None:
        sys.exit("Error: Hardware address not found in ARP table, IP will have to be specified manually.")

print("Capturing screenshot..")
filename = output_filename('DM3058', 'bmp')
file_length = dm3058_screenshot(INSTRUMENT_IP, "%s/%s" % (filepath, filename))
if not file_length:
    sys.exit('Capture failed')

print("Saved screenshot to %s (%.1fKB)" % (filename, file_length/1024.0))
if args.preview:
    image_preview(filename)
if args.imgur:
    imgur_post(filename, "DM3058 Screen Capture")
