#!/usr/bin/env python3

from telnetlib_receive_all import Telnet
from keysight import *
from common import *
import time
import sys
import os

INSTRUMENT_PORT = 5025

# Check command line parameters
script_name = os.path.basename(sys.argv[0])
filepath = os.getcwd()

def print_help():
    global script_name
    print ("Usage:")
    print ("    " + script_name + " [psu_ip]")
    print ()
    print ("Usage examples:")
    print ("    " + script_name)
    print ("    " + script_name + " 192.168.1.3")
    print ()
    print ("This program captures the screen of the power supply")
    print ("    as a BMP file with a timestamp in the file name.")
    print ()

if len(sys.argv) == 1:
    INSTRUMENT_IP = find_arp(KEYSIGHT_OUI)
    if INSTRUMENT_IP is None:
        print_help()
        sys.exit("Error: Hardware address not found in ARP table, IP will have to be specified manually.")
elif len(sys.argv) == 2:
        INSTRUMENT_IP = sys.argv[1]
else:
    print_help()
    sys.exit("Error: Wrong command line parameters.")

if not instrument_ping(INSTRUMENT_IP):
    sys.exit("Error: No response pinging address " + INSTRUMENT_IP)

tn = Telnet(INSTRUMENT_IP, INSTRUMENT_PORT)
instrument_id = command(tn, "*IDN?").decode().rstrip()
tn.close()

instrument_manufacturer,instrument_model,instrument_serial,instrument_fw = instrument_id.split(",")

print("Found %s %s at %s" % (instrument_manufacturer, instrument_model, INSTRUMENT_IP))
print("Downloading screenshot..")

timestamp = time.strftime("%Y-%m-%d_%H:%M:%S", time.localtime())
filename = "E36312A_%s.bmp" % (timestamp)

file_length = e36312a_screenshot(INSTRUMENT_IP, "%s/%s" % (filepath, filename))

if file_length is not None:
    print("Saved screenshot to %s" % (filename))
else:
    print("Download failed.")
